"""Generate traffic demand for the intersection (S33, PRD §12.2, ADR-010).

Demand is generated, not hand-written, for the same reason the network is: the
arrival rate decides whether the intersection is undersaturated, saturated or
gridlocked, and that single choice decides whether "PPO beats Webster by 10%" is
a meaningful claim or an artifact of a regime nobody declared.

Three regimes are defined here and all three are benchmarked (FR-R08). Reporting
one number from one arrival rate is how a controller comparison gets rigged
without anybody intending to.

    python scripts/build_sumo_demand.py --regime saturated --seed 42

Seeds matter: `randomTrips`-style demand is stochastic, and the 30-seed benchmark
(FR-R07) varies exactly this.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

OUT = Path("simulation/networks")
APPROACHES = ("N", "S", "E", "W")

# Turn ratios: most traffic goes straight. Left and right are unprotected
# movements under the two-phase program, which is realistic for the modelled
# intersection and is why they are a minority rather than absent.
TURN_RATIOS = {"straight": 0.60, "right": 0.25, "left": 0.15}

OPPOSITE = {"N": "S", "S": "N", "E": "W", "W": "E"}
RIGHT_OF = {"N": "W", "W": "S", "S": "E", "E": "N"}
LEFT_OF = {v: k for k, v in RIGHT_OF.items()}


@dataclass(frozen=True)
class Regime:
    """One demand level, in vehicles per hour per approach.

    **Calibrated by measurement, not estimated.** The first version of this file
    derived the levels from a back-of-envelope capacity figure (~2,100 PCU/h per
    approach) and labelled 1,000 veh/h/approach "saturated". A sweep under the
    fixed-time baseline showed that regime completing only **73%** of trips —
    which is not saturation, it is breakdown, and every comparison run there
    would have been a comparison of how gracefully methods fail.

    Measured with `Fixed(green_s=30)`, 1200 s, seed 42:

        veh/h/appr   mean wait   mean queue   arrived
               400       10.6 s          4.4      0.99
               600       13.4 s          8.0      1.00
               700       18.9 s         13.4      0.99
               800       49.2 s         42.4      0.85   <- knee
               900       74.3 s         71.7      0.81
              1000       90.2 s         95.2      0.76

    The capacity knee under fixed-time is between **700 and 800**. The regimes
    below bracket it deliberately: one clearly under, one at the knee where
    timing decides the outcome, one clearly over.
    """

    name: str
    veh_per_hour_per_approach: int
    note: str


REGIMES = {
    "light": Regime("light", 400, "undersaturated — fixed-time clears 99% of "
                                  "trips, so any difference here is real and "
                                  "not an artifact of overload"),
    "saturated": Regime("saturated", 750, "at the measured capacity knee, where "
                                          "signal timing decides the outcome. "
                                          "The headline comparison is made here"),
    "oversaturated": Regime("oversaturated", 1000, "past the knee — fixed-time "
                                                   "completes 76% of trips. "
                                                   "Tests graceful degradation, "
                                                   "not optimality"),
}


def routes_xml(regime: Regime, duration_s: int, seed: int) -> str:
    """Flows for every approach and turn movement, drawn from the india_mix."""
    rows = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- GENERATED by scripts/build_sumo_demand.py — do not edit.",
        f"     regime={regime.name}  {regime.veh_per_hour_per_approach} veh/h/approach"
        f"  seed={seed}",
        f"     {regime.note} -->",
        "<routes>",
    ]

    for origin in APPROACHES:
        destinations = {
            "straight": OPPOSITE[origin],
            "right": RIGHT_OF[origin],
            "left": LEFT_OF[origin],
        }
        for movement, share in TURN_RATIOS.items():
            destination = destinations[movement]
            rows.append(
                f'    <route id="r_{origin}_{movement}" '
                f'edges="{origin}2C C2{destination}"/>'
            )

    rows.append("")
    for origin in APPROACHES:
        for movement, share in TURN_RATIOS.items():
            per_hour = regime.veh_per_hour_per_approach * share
            rows.append(
                f'    <flow id="f_{origin}_{movement}" route="r_{origin}_{movement}" '
                f'type="india_mix" begin="0" end="{duration_s}" '
                f'vehsPerHour="{per_hour:.1f}" departLane="free" '
                f'departSpeed="max" departPosLat="random"/>'
            )
            # departPosLat="random" matters: entering vehicles take a lateral
            # position rather than snapping to lane centre, which is what lets
            # the sublane model produce filtering from the first step instead of
            # after a lane change (ADR-010).

    rows.append("</routes>")
    return "\n".join(rows) + "\n"


def build(regime_name: str, out: Path = OUT, *, duration_s: int = 3600,
          seed: int = 42) -> dict:
    if regime_name not in REGIMES:
        raise ValueError(
            f"unknown regime {regime_name!r}; expected one of {sorted(REGIMES)}"
        )
    regime = REGIMES[regime_name]
    out.mkdir(parents=True, exist_ok=True)

    path = out / f"demand_{regime.name}.rou.xml"
    path.write_text(routes_xml(regime, duration_s, seed), encoding="utf-8")

    total = regime.veh_per_hour_per_approach * len(APPROACHES)
    return {
        "path": path,
        "regime": regime,
        "total_veh_per_hour": total,
        "duration_s": duration_s,
        "seed": seed,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--regime", default="saturated", choices=sorted(REGIMES))
    parser.add_argument("--all", action="store_true", help="generate all regimes")
    parser.add_argument("--duration", type=int, default=3600)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args(argv)

    names = sorted(REGIMES) if args.all else [args.regime]
    for name in names:
        info = build(name, args.out, duration_s=args.duration, seed=args.seed)
        r = info["regime"]
        print(f"  {r.name:14} {r.veh_per_hour_per_approach:>5} veh/h/approach"
              f"   {info['total_veh_per_hour']:>5} total   -> {info['path'].name}")
        print(f"                 {r.note}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
