"""Generate the four-way intersection SUMO network (S32, PRD §13, ADR-010/011/012).

Everything here is generated from parameters, never hand-edited. A network XML
edited by hand is a number that exists in exactly one place and is checked by
nobody — and three of this project's parameters are load-bearing for results:

* **approach width** decides the Webster saturation flow, which is expressed per
  metre of width for non-lane-disciplined traffic (ADR-012). Get the width wrong
  and every `S = kW` figure in the RL benchmark is wrong with it.
* **max green plus all-red** decides the worst-case lane wait, which `spec.yaml`
  asserts and FR-R04's starvation penalty depends on.
* **`--lateral-resolution`** is what makes two-wheelers filter (ADR-010). Without
  it the simulation is lane-disciplined and does not model the traffic the whole
  project is about.

    python scripts/build_sumo_network.py
    python scripts/build_sumo_network.py --check     # verify, do not write

Outputs land in `simulation/networks/`. They are committed, because a reviewer
should be able to open the network without installing SUMO — but they are always
regenerated, never edited.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from simulation.sumo_tools import sumo_binary, sumo_version  # noqa: E402

OUT = Path("simulation/networks")
APPROACHES = {"N": (0, 1), "S": (0, -1), "E": (1, 0), "W": (-1, 0)}


@dataclass(frozen=True)
class NetworkSpec:
    """Defaults are chosen, not arbitrary — see the notes on each."""

    approach_m: int = 250
    # Long enough to hold a HIGH-congestion queue (>15 vehicles/lane, §14.1)
    # without vehicles backing off the edge and vanishing from the counts. A
    # short approach silently truncates exactly the state the model must predict.

    lanes: int = 2
    lane_width_m: float = 3.2
    # 2 x 3.2 = 6.4 m approach width. Deliberately ABOVE 5.5 m, because
    # IRC:SP-41-1994's S = 525W is stated valid only above that, and ADR-012's
    # sweep spans 525W-1283W. Below 5.5 m the narrow-width form applies instead
    # and the sweep would be comparing two different formulas.

    speed_mps: float = 13.89          # 50 km/h urban arterial
    min_green_s: int = 10             # spec.yaml signal.min_green_s
    max_green_s: int = 90
    yellow_s: int = 3
    all_red_s: int = 3                # spec.yaml signal.all_red_s, FR-A04
    lateral_resolution_m: float = 0.8  # ADR-010 — the filtering behaviour

    @property
    def approach_width_m(self) -> float:
        """Feeds Webster's S = k x W. ADR-012 sweeps k, never this."""
        return self.lanes * self.lane_width_m

    @property
    def worst_red_s(self) -> int:
        """Longest an approach is red under strict alternation (amendment A27).

        Its own green ends, then: all-red, the other phase's green, the other
        phase's **yellow**, all-red.

        Its own yellow is excluded — traffic still discharges during it, so it
        is not wait time. The other phase's yellow is included, because this
        approach is red throughout it. That asymmetry is why the figure is 99
        rather than 96 (yellow ignored entirely) or 102 (both yellows counted).

        Computed, never remembered: conflating cycle length with lane wait
        produced a withdrawn claim once already (P6), and omitting yellow
        produced a second wrong figure (A27).
        """
        return self.max_green_s + self.yellow_s + 2 * self.all_red_s

    @property
    def max_cycle_s(self) -> int:
        """Webster's clamp ceiling (ADR-011). Both phases at maximum green."""
        return 2 * (self.max_green_s + self.yellow_s + self.all_red_s)


def nodes_xml(spec: NetworkSpec) -> str:
    rows = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- GENERATED by scripts/build_sumo_network.py — do not edit -->",
        "<nodes>",
        '    <node id="C" x="0" y="0" type="traffic_light" tlType="static"/>',
    ]
    for name, (dx, dy) in APPROACHES.items():
        x, y = dx * spec.approach_m, dy * spec.approach_m
        rows.append(f'    <node id="{name}" x="{x}" y="{y}" type="priority"/>')
    rows.append("</nodes>")
    return "\n".join(rows) + "\n"


def edges_xml(spec: NetworkSpec) -> str:
    rows = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- GENERATED by scripts/build_sumo_network.py — do not edit -->",
        "<edges>",
    ]
    for name in APPROACHES:
        common = (
            f'numLanes="{spec.lanes}" speed="{spec.speed_mps}" '
            f'width="{spec.lane_width_m}"'
        )
        # Inbound edge id is "<approach>2C" — the lane ids derived from it are
        # what the 16-dim PPO state indexes by, so they are part of a contract.
        rows.append(f'    <edge id="{name}2C" from="{name}" to="C" {common}/>')
        rows.append(f'    <edge id="C2{name}" from="C" to="{name}" {common}/>')
    rows.append("</edges>")
    return "\n".join(rows) + "\n"


def _strip_generation_timestamp(net: Path) -> None:
    """Remove netconvert's wall-clock stamp from the generated network.

    netconvert has no option to suppress it, and the file is committed. Left in,
    every regeneration produces a diff whose only content is the current time —
    and a file that always shows a diff is a file whose diffs stop being read.

    The SUMO **version** is deliberately kept: that changing is a real event
    that should be visible, because a version bump can move simulation results.
    """
    text = net.read_text(encoding="utf-8")
    net.write_text(
        re.sub(
            r"generated on [0-9T:.+\-]+ by",
            "generated by scripts/build_sumo_network.py using",
            text,
            count=1,
        ),
        encoding="utf-8",
    )


def read_tls_program(net: Path) -> list[tuple[float, str]]:
    """Read back `(duration, state)` for every phase netconvert produced.

    The signal program is **generated by netconvert, not hand-written**. The
    first attempt here did write it by hand and netconvert rejected it with
    `Invalid linkIndex 8 for traffic light 'C' with 8 links` — because the link
    count depends on how many connections netconvert infers at the junction,
    which depends on lane count, turn permissions and geometry.

    Hard-coding a state string means guessing that number. Guessing it right
    today and wrong after any geometry change would be worse: SUMO would accept a
    same-length string that greens the wrong movements, and the simulation would
    run happily while modelling an intersection nobody designed.

    So netconvert derives it and this function reads it back, so the structure
    can be **asserted** rather than assumed.
    """
    import xml.etree.ElementTree as ET

    root = ET.parse(net).getroot()
    logic = root.find(".//tlLogic")
    if logic is None:
        raise RuntimeError(f"no traffic light program in {net}")
    return [
        (float(p.get("duration")), p.get("state")) for p in logic.findall("phase")
    ]


def green_phases(program: list[tuple[float, str]]) -> list[tuple[float, str]]:
    """Phases that give somebody a green. Yellow and all-red are excluded."""
    return [(d, s) for d, s in program if "G" in s or "g" in s]


def vtypes_xml() -> str:
    """PRD §12.2 mix with ADR-010 dimensions and lateral behaviour.

    `latAlignment="arbitrary"`, `lcSublane` and `minGapLat` are what let a
    motorcycle sit beside a car rather than behind it. Without them the mix is
    cosmetic: different lengths queueing in single file is not the traffic this
    project claims to model.
    """
    return """<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/build_sumo_network.py — do not edit.
     Proportions: PRD §12.2. Dimensions and lateral behaviour: ADR-010.
     PCE values (spec.yaml webster.pce) feed the Webster baseline, not SUMO. -->
<additional>
    <vType id="motorcycle"    vClass="motorcycle" length="2.0"  width="0.8"
           accel="3.0" decel="5.0" maxSpeed="16" latAlignment="arbitrary"
           lcSublane="1.0" minGapLat="0.2"/>
    <vType id="auto_rickshaw" vClass="passenger"  length="2.6"  width="1.4"
           accel="2.0" decel="4.0" maxSpeed="14" latAlignment="arbitrary"
           lcSublane="0.8" minGapLat="0.3"/>
    <vType id="e_rickshaw"    vClass="passenger"  length="2.8"  width="1.4"
           accel="1.6" decel="4.0" maxSpeed="11" latAlignment="arbitrary"
           lcSublane="0.8" minGapLat="0.3"/>
    <vType id="car"           vClass="passenger"  length="4.3"  width="1.8"
           accel="2.6" decel="4.5" maxSpeed="20"/>
    <vType id="bus"           vClass="bus"        length="12.0" width="2.5"
           accel="1.2" decel="4.0" maxSpeed="16"/>
    <vType id="truck"         vClass="truck"      length="7.1"  width="2.4"
           accel="1.3" decel="4.0" maxSpeed="16"/>

    <!-- PRD §12.2 proportions, renormalised over the 6 driving classes.
         Pedestrians (7%) and cattle (1%) are detection classes, not SUMO
         vehicles; modelling them is out of scope and saying so is better than
         a silent omission.

         Declared as id + probability lists, NOT as nested <vType> elements.
         Nesting re-declares each type and SUMO rejects it with
         "Another vehicle type (or distribution) with the id 'car' exists." -->
    <vTypeDistribution id="india_mix"
        vTypes="car motorcycle auto_rickshaw e_rickshaw truck bus"
        probabilities="0.38 0.33 0.16 0.05 0.05 0.03"/>
</additional>
"""


def sumocfg_xml(spec: NetworkSpec) -> str:
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/build_sumo_network.py — do not edit -->
<configuration>
    <input>
        <net-file value="intersection.net.xml"/>
        <additional-files value="vtypes.add.xml"/>
    </input>
    <processing>
        <!-- ADR-010: continuous lateral position. This single value is the
             difference between modelling Indian traffic and modelling a lane-
             disciplined approximation of it. -->
        <lateral-resolution value="{spec.lateral_resolution_m}"/>
        <collision.action value="warn"/>
        <time-to-teleport value="-1"/>
        <!-- Teleporting is DISABLED. A gridlocked vehicle that teleports away
             quietly removes the congestion the agent is being scored on, and
             turns a failure into a good-looking result. -->
    </processing>
    <time>
        <begin value="0"/>
        <step-length value="1.0"/>
    </time>
    <report>
        <no-step-log value="true"/>
        <duration-log.statistics value="true"/>
    </report>
</configuration>
"""


def build(spec: NetworkSpec, out: Path = OUT) -> dict:
    out.mkdir(parents=True, exist_ok=True)
    for name, content in {
        "intersection.nod.xml": nodes_xml(spec),
        "intersection.edg.xml": edges_xml(spec),
        "vtypes.add.xml": vtypes_xml(),
        "intersection.sumocfg": sumocfg_xml(spec),
    }.items():
        (out / name).write_text(content, encoding="utf-8")

    net = out / "intersection.net.xml"
    command = [
        str(sumo_binary("netconvert")),
        "--node-files", str(out / "intersection.nod.xml"),
        "--edge-files", str(out / "intersection.edg.xml"),
        "--output-file", str(net),
        "--no-turnarounds", "true",
        "--default.lanewidth", str(spec.lane_width_m),
        "--tls.default-type", "static",
        # Two green phases, NS and EW. `opposites` greens opposing approaches
        # together; a zero left-turn phase suppresses the protected-left phase
        # netconvert would otherwise add, because PRD §13.1's action space is
        # (phase, duration) over exactly two phases. Lefts remain permitted,
        # they just do not get a stage of their own.
        "--tls.layout", "opposites",
        "--tls.green.time", str(spec.min_green_s),
        "--tls.yellow.time", str(spec.yellow_s),
        "--tls.allred.time", str(spec.all_red_s),
        "--tls.left-green.time", "0",
    ]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"netconvert failed:\n{result.stderr.strip()}")

    _strip_generation_timestamp(net)
    program = read_tls_program(net)
    greens = green_phases(program)
    if len(greens) != 2:
        raise RuntimeError(
            f"expected exactly 2 green phases (NS and EW) but netconvert "
            f"produced {len(greens)}:\n"
            + "\n".join(f"    {d:>5.1f}s  {s}" for d, s in program)
            + "\n  PRD §13.1's action space is 12 discrete = 2 phases x 6 "
              "durations. A third phase makes the action space wrong and every "
              "trained PPO checkpoint invalid."
        )

    return {
        "net": net,
        "sumo_version": sumo_version(),
        "approach_width_m": spec.approach_width_m,
        "worst_red_s": spec.worst_red_s,
        "max_cycle_s": spec.max_cycle_s,
        "program": program,
        "links": len(program[0][1]),
        "netconvert_warnings": result.stderr.strip(),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--out", type=Path, default=OUT)
    parser.add_argument("--approach-m", type=int, default=NetworkSpec.approach_m)
    parser.add_argument("--lanes", type=int, default=NetworkSpec.lanes)
    args = parser.parse_args(argv)

    spec = NetworkSpec(approach_m=args.approach_m, lanes=args.lanes)
    info = build(spec, args.out)

    print(f"  {info['sumo_version']}")
    print(f"  wrote {info['net']}")
    print(f"  approach width      {info['approach_width_m']:.1f} m"
          f"   (Webster S = k x W, ADR-012 sweeps k)")
    print(f"  worst red per lane  {info['worst_red_s']} s"
          f"   (other green + other yellow + 2 x all-red)")
    print(f"  max cycle           {info['max_cycle_s']} s"
          f"   (Webster clamp ceiling, ADR-011)")
    print(f"  junction links      {info['links']}")
    print("  signal program:")
    for duration, state in info["program"]:
        kind = "GREEN " if ("G" in state or "g" in state) else (
            "yellow" if "y" in state else "allred")
        print(f"    {kind}  {duration:>5.1f}s  {state}")
    if info["netconvert_warnings"]:
        print(f"\n  netconvert said:\n{info['netconvert_warnings']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
