"""End-to-end pipeline demonstration on synthetic data.

    python scripts/demo_pipeline.py

Runs the whole corpus chain — detections through to metrics — with no video, no
detector, no PyTorch and no GPU. Standard library only. Ten seconds.

**Why this exists.** Every module has unit tests, and none of them exercised the
modules *together*. A pile of individually-correct parts is not a pipeline, and
the defects that matter live at the seams. This is the first thing that composes
them, and it is meant to be run rather than read.

What it does NOT prove: that the detector works, that real traffic transitions
often enough to be learnable, or that any model helps. Those need Week-2 pilots
and real footage. This proves the plumbing carries water.
"""

from __future__ import annotations

import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from mfstnet.corpus import (  # noqa: E402
    Polygon,
    SequenceRecord,
    WindowGeometry,
    assign_splits,
    density_band,
    label_from_count,
    load_source,
    sequences_from_clip,
    smooth_counts,
    validate_corpus,
)
from mfstnet.corpus.counting import Detection, count_clip  # noqa: E402
from mfstnet.metrics import evaluate, format_confusion_matrix  # noqa: E402

SEED = 42
N_CLIPS = 24
CLIP_MINUTES = 12

LANES = [
    Polygon("N", ((0.05, 0.05), (0.45, 0.05), (0.45, 0.45), (0.05, 0.45))),
    Polygon("S", ((0.55, 0.55), (0.95, 0.55), (0.95, 0.95), (0.55, 0.95))),
    Polygon("E", ((0.55, 0.05), (0.95, 0.05), (0.95, 0.45), (0.55, 0.45))),
    Polygon("W", ((0.05, 0.55), (0.45, 0.55), (0.45, 0.95), (0.05, 0.95))),
]


def rule(title: str) -> None:
    print(f"\n{'=' * 72}\n{title}\n{'=' * 72}")


def synthetic_frame(rng: random.Random, occupancy: dict[str, int]) -> list[Detection]:
    """Place `occupancy[lane]` vehicles inside each lane, plus junction traffic.

    The junction vehicles exist so the unassigned rate is non-zero and realistic —
    a pipeline that never produces one has not been tested against the case that
    signals badly drawn polygons.
    """
    dets: list[Detection] = []
    for poly in LANES:
        x0, y0, x1, y1 = poly.bbox()
        for _ in range(occupancy[poly.name]):
            cx = rng.uniform(x0 + 0.03, x1 - 0.03)
            cy = rng.uniform(y0 + 0.03, y1 - 0.03)
            cls = rng.choices(
                ["car", "motorcycle", "auto-rickshaw", "bus"], weights=[35, 40, 20, 5]
            )[0]
            dets.append(Detection(cls, rng.uniform(0.4, 0.95),
                                  cx - 0.015, cy - 0.015, cx + 0.015, cy + 0.015))
    for _ in range(rng.randint(0, 2)):  # mid-junction, belongs to no approach
        dets.append(Detection("car", 0.8, 0.48, 0.48, 0.52, 0.52))
    return dets


def main() -> int:
    rng = random.Random(SEED)
    g = WindowGeometry()

    rule("1. SOURCE  ·  registry, polygon validation, clip arithmetic")
    source = load_source({
        "source_id": "synthetic_demo",
        "kind": "dev",
        "licence": "synthetic - generated by this script, no third-party rights",
        "clips": [
            {"clip_id": f"clip{i:02d}", "path": f"synthetic/{i}.mp4",
             "duration_s": CLIP_MINUTES * 60}
            for i in range(N_CLIPS)
        ],
        "lanes": {p.name: p.vertices for p in LANES},
    })
    print(f"  source        {source.source_id}  (kind={source.kind})")
    print(f"  lanes         {len(source.lanes)}, validated disjoint")
    print(f"  clips         {len(source.clips)} x {CLIP_MINUTES} min")
    print(f"  one sample    {g.T} frames spanning {g.observation_span_s}s, "
          f"label at +{g.horizon_s}s = frame index {g.label_offset_frames}")
    print(f"  minimum clip  {g.min_clip_s}s   (a 300s clip yields "
          f"{g.count_for_duration(300)} sequences)")
    print(f"  expected      {source.total_sequences()} sequences")

    rule("2. COUNT  ·  synthetic detections through centroid-in-polygon")
    frames_per_clip = g.frames_for_duration(CLIP_MINUTES * 60)
    counts_by_clip: dict[str, dict[str, list[int]]] = {}
    unassigned_by_clip: dict[str, float] = {}

    for clip in source.clips:
        level = {p.name: rng.randint(0, 18) for p in LANES}
        frames = []
        for _ in range(frames_per_clip):
            for name in level:  # random walk so classes genuinely transition
                level[name] = max(0, min(28, level[name] + rng.randint(-3, 3)))
            frames.append(synthetic_frame(rng, level))
        series, rate = count_clip(frames, LANES, min_confidence=0.25,
                                  exclude_classes=frozenset({"rider"}))
        counts_by_clip[clip.clip_id] = series
        unassigned_by_clip[clip.clip_id] = rate

    sample = counts_by_clip["clip00"]["N"][:12]
    print(f"  frames/clip   {frames_per_clip}")
    print(f"  raw N counts  {sample}")
    print(f"  smoothed      {smooth_counts(sample)}   (median, 3-frame)")
    print(f"  unassigned    mean {sum(unassigned_by_clip.values()) / len(unassigned_by_clip):.1%} "
          f"(mid-junction vehicles belong to no approach)")

    rule("3. LABEL + WINDOW  ·  A15 arithmetic, splits cut by clip")
    smoothed = {c: {ln: smooth_counts(s) for ln, s in lanes.items()}
                for c, lanes in counts_by_clip.items()}
    split_of = assign_splits([c.clip_id for c in source.clips], seed=SEED)

    records: list[SequenceRecord] = []
    for clip in source.clips:
        for seq in sequences_from_clip(clip.clip_id, frames_per_clip, g):
            last = seq.frame_indices[-1]
            lab = tuple(label_from_count(smoothed[clip.clip_id][p.name][seq.label_index])
                        for p in LANES)
            now = tuple(label_from_count(smoothed[clip.clip_id][p.name][last])
                        for p in LANES)
            mean_total = sum(smoothed[clip.clip_id][p.name][i]
                             for p in LANES for i in seq.frame_indices) / len(seq.frame_indices)
            records.append(SequenceRecord(
                seq_id=f"{clip.clip_id}_{seq.start_index}",
                clip_id=clip.clip_id,
                split=split_of[clip.clip_id],
                labels=tuple(int(x) for x in lab),
                labels_now=tuple(int(x) for x in now),
                density_band=density_band(mean_total),
                label_origin="verified" if split_of[clip.clip_id] == "test" else "auto",
            ))

    print(f"  sequences     {len(records)} built (expected {source.total_sequences()})")
    print(f"  splits        by CLIP, never by sequence "
          f"(consecutive windows share 54 of 60 frames)")

    rule("4. VALIDATE  ·  seven gates, blocking vs advisory")
    report = validate_corpus(records, unassigned_by_clip)
    print(report)
    print(f"\n  blocking failures: {len(report.blocking_failures)}   "
          f"advisories: {len(report.advisories)}")

    rule("5. METRICS  ·  against the Naive last-value baseline")
    test = [r for r in records if r.split == "test"]
    truth = [x for r in test for x in r.labels]
    naive = [x for r in test for x in r.labels_now]   # 14.3's lower bound, free
    res = evaluate(truth, naive)

    print(f"  test sequences {len(test)} from "
          f"{len({r.clip_id for r in test})} clips  <- effective n for the bootstrap")
    print()
    print(format_confusion_matrix(res.confusion))
    print()
    print(f"  accuracy {res.accuracy:.3f}   macro F1 {res.macro_f1:.3f}   "
          f"QWK {res.qwk:.3f}")
    print(f"  ordinal MAE {res.ordinal_mae:.3f}   off-by-two {res.off_by_two_rate:.3f}")
    for w in res.warnings:
        print(f"  WARNING  {w}")

    rule("VERDICT")
    print("  The chain composes. Detections -> counts -> labels -> windows -> "
          "splits -> gates -> metrics.")
    print()
    print("  What this does NOT show: whether the detector works, whether real")
    print("  traffic transitions often enough to be learnable, or whether any model")
    print("  helps. Those need the Week-2 pilots and real footage.")
    print()
    print(f"  Naive baseline scores {res.accuracy:.1%} here. On real footage that")
    print("  number is the bar every model must clear - and if it is ~95%, the task")
    print("  is degenerate and the transition gate will say so (PRD A17).")

    return 0 if report.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
