"""Convert TrafficCAM polygon annotations to YOLO detection labels (S17).

    python scripts/prepare_trafficcam.py --src "D:/traffic dataset/TrafficCAM" \
        --out data/trafficcam_yolo

[TrafficCAM](https://github.com/Math-ML-X/TrafficCAM) is **human-annotated
instance segmentation of Indian traffic** — 1920x1080 LabelMe polygons, roughly
50 objects a frame, from elevated fixed cameras in Bengaluru, Delhi, Mumbai,
Noida and NITK.

**This is the deployment viewpoint, annotated by people.** Every other source
this project has used is a compromise on one of those two axes: IDD is largely
dashcam, BMD-45 is elevated but stills, and the ITD pseudo-labels are the right
viewpoint but generated by a model whose bus and truck predictions were 65% and
43% spurious on the same kind of footage. TrafficCAM is both, and it did not
cost us an annotation budget.

## What it is not

**It is not a forecasting corpus.** A sequence is 30 frames at stride 2 — about
two seconds. A15 requires 360 s of continuous fixed-camera video for one
prediction window, so TrafficCAM is 180 times too short per sequence. It trains
the detector; it cannot build the MFSTNet corpus.

## Classes

Seven labels map onto six of ours. `e_rickshaw` and `cattle` appear in neither
TrafficCAM nor ITD, so both remain unsupported by every external source and can
only come from IDD or our own annotation.

`LCV` folds into `truck` because our label set has no light-commercial class;
that is a real loss of granularity and is recorded rather than hidden.

## Polygons to boxes

A YOLO detection label is the axis-aligned extent of the polygon. Converting
discards the mask, which is fine for this project — but the masks are the
reason this dataset could later support a segmentation arm, and they are left
untouched in `--src`.
"""

from __future__ import annotations

import argparse
import collections
import json
import random
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

CLASSES = ["car", "motorcycle", "auto_rickshaw", "e_rickshaw",
           "bus", "truck", "pedestrian", "cattle"]

# TrafficCAM label -> ours. Anything absent here is dropped LOUDLY, not guessed,
# and that design paid for itself on the first run: a strict map reported 3,140
# dropped annotations, of which **1,700 were `e-Rickshaw`**.
#
# `e_rickshaw` is the class this project has never been able to evaluate — zero
# test boxes in IDD, zero in BMD-45, `evaluated: False` in every metrics CSV,
# and absent from ITD entirely. It was here the whole time under a different
# spelling. A permissive default that silently folded unknown labels into a
# nearest neighbour would have buried it.
#
# The rest are annotator spelling variants of classes already present.
LABEL_MAP = {
    "LMV": "car",
    "MotorBike": "motorcycle",
    "Bike": "motorcycle",
    "Motor Bike": "motorcycle",
    "Moterbike": "motorcycle",
    "Auto": "auto_rickshaw",
    "e-Rickshaw": "e_rickshaw",
    "Bus": "bus",
    "Truck": "truck",
    "LCV": "truck",          # no light-commercial class in our label set
    "Tractor": "truck",      # Indo-HCM tabulates it separately (PCU 7.0); we
                             # have no tractor class, so it joins the large
                             # commercial vehicles rather than being discarded
    "Pedestrian": "pedestrian",
    "Pesestrian": "pedestrian",
}


def to_yolo_box(points, width: int, height: int):
    """Axis-aligned extent of a polygon, normalised, clamped to the frame."""
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    x1, x2 = max(0.0, min(xs)), min(float(width), max(xs))
    y1, y2 = max(0.0, min(ys)), min(float(height), max(ys))
    if x2 <= x1 or y2 <= y1:
        return None
    return ((x1 + x2) / 2 / width, (y1 + y2) / 2 / height,
            (x2 - x1) / width, (y2 - y1) / height)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--src", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--splits", type=float, nargs=3, default=(0.70, 0.15, 0.15),
                        help="train/val/test, FR-D05 stratified 70/15/15")
    args = parser.parse_args(argv)

    index = {name: number for number, name in enumerate(CLASSES)}
    sequences: list[Path] = []
    for area in ("Fully_annotate/Fully_annotate",
                 "FirstFrame_annotate-1/FirstFrame_annotate-1"):
        base = args.src / area
        if not base.is_dir():
            print(f"  SKIP {area} — not present")
            continue
        sequences += [p for p in sorted(base.iterdir())
                      if p.is_dir() and not p.name.startswith(".")]
    if not sequences:
        raise SystemExit(f"no sequences under {args.src}")

    # **Split by CAMERA SESSION, not by sequence.** The first version of this
    # split by sequence, on the reasoning that 30 frames two seconds apart are
    # near-duplicates. That reasoning was right and the unit was still wrong.
    #
    # Sequence names are `<session>_<unix timestamp>`, and measured across the
    # dataset the median gap between consecutive sequences within a session is
    # **3 to 8 seconds**: ND_O4 is 74 sequences at a 3 s median, NT4_O2 is 91 at
    # 4 s, BLR is 27 at 8 s. They are consecutive clips of one continuous
    # recording, not independent scenes. Splitting by sequence puts frames three
    # seconds apart into train and test and reports an inflated number.
    #
    # The honest independent unit is the session. There are only about thirteen
    # of them, which is a real limitation of this dataset and is reported below
    # rather than hidden by a split that makes it look like hundreds.
    def session_of(path: Path) -> str:
        match = re.match(r"(.+?)_\d{9,10}", path.name)
        return match.group(1) if match else path.name

    groups: dict[str, list[Path]] = collections.defaultdict(list)
    for sequence in sequences:
        groups[session_of(sequence)].append(sequence)

    # Assigning whole sessions in shuffled order splits the *sessions* 70/15/15
    # but not the frames, because a `Fully_annotate` session carries 30 frames
    # per sequence and a `FirstFrame` session carries one. Measured on the first
    # attempt: 922 train frames against 1,530 test — a test split larger than
    # the training set.
    #
    # So sessions are packed greedily, largest first, each going to whichever
    # split is furthest below its frame-count target. Grouping is still by
    # session, so no leakage is traded away for the balance.
    weights = {name: sum(len(list(s.glob("*.json"))) for s in members)
               for name, members in groups.items()}
    rng = random.Random(args.seed)
    names = sorted(groups)
    rng.shuffle(names)
    names.sort(key=lambda n: -weights[n])

    total_frames = sum(weights.values())
    targets = dict(zip(("train", "val", "test"),
                       (share * total_frames for share in args.splits)))
    running = {"train": 0, "val": 0, "test": 0}
    assignment = {}
    split_of_session = {}
    for session in names:
        split = max(targets, key=lambda s: targets[s] - running[s])
        running[split] += weights[session]
        split_of_session[session] = split
        for sequence in groups[session]:
            assignment[sequence] = split

    print(f"  {len(names)} camera session(s) -> "
          f"{sum(1 for s in split_of_session.values() if s == 'train')} train / "
          f"{sum(1 for s in split_of_session.values() if s == 'val')} val / "
          f"{sum(1 for s in split_of_session.values() if s == 'test')} test")
    for split in ("train", "val", "test"):
        members = sorted(s for s, v in split_of_session.items() if v == split)
        print(f"    {split:<6} {', '.join(members)}")

    for split in ("train", "val", "test"):
        (args.out / "images" / split).mkdir(parents=True, exist_ok=True)
        (args.out / "labels" / split).mkdir(parents=True, exist_ok=True)

    tally: dict[str, collections.Counter] = {
        s: collections.Counter() for s in ("train", "val", "test")}
    frames = collections.Counter()
    unmapped: collections.Counter = collections.Counter()
    dropped = 0

    for sequence in sequences:
        split = assignment[sequence]
        for annotation in sorted(sequence.glob("*.json")):
            image = annotation.with_suffix(".jpg")
            if not image.is_file():
                continue
            data = json.loads(annotation.read_text(encoding="utf-8"))
            width, height = data["imageWidth"], data["imageHeight"]

            rows = []
            for shape in data.get("shapes", []):
                name = LABEL_MAP.get(shape["label"])
                if name is None:
                    unmapped[shape["label"]] += 1
                    continue
                box = to_yolo_box(shape["points"], width, height)
                if box is None:
                    dropped += 1
                    continue
                rows.append("%d %.6f %.6f %.6f %.6f" % (index[name], *box))
                tally[split][name] += 1
            if not rows:
                continue

            stem = f"{sequence.name}_{annotation.stem}"
            shutil.copyfile(image, args.out / "images" / split / f"{stem}.jpg")
            (args.out / "labels" / split / f"{stem}.txt").write_text(
                "\n".join(rows) + "\n", encoding="utf-8")
            frames[split] += 1

    yaml = args.out / "data.yaml"
    yaml.write_text(
        "# GENERATED by scripts/prepare_trafficcam.py — do not edit.\n"
        "# Split by SEQUENCE (seed %d), never by frame: 30 frames two seconds\n"
        "# apart from one camera are near-duplicates.\n"
        "path: %s\ntrain: images/train\nval: images/val\ntest: images/test\n"
        "nc: %d\nnames: %s\n"
        % (args.seed, args.out.resolve().as_posix(), len(CLASSES), CLASSES),
        encoding="utf-8")

    print(f"\n  {len(sequences)} sequences -> "
          f"{frames['train']} train / {frames['val']} val / {frames['test']} test frames")
    print(f"\n  {'class':<16}{'train':>9}{'val':>8}{'test':>8}")
    for name in CLASSES:
        counts = [tally[s][name] for s in ("train", "val", "test")]
        if sum(counts):
            print(f"  {name:<16}{counts[0]:>9}{counts[1]:>8}{counts[2]:>8}")
    for name in CLASSES:
        if tally["train"][name] and not tally["test"][name]:
            print()
            print(f"  WARNING: {name} has {tally['train'][name]} train boxes but "
                  f"NONE in test. With so few camera sessions a group split can "
                  f"put a whole class on one side. It cannot be evaluated — "
                  f"change --seed, or accept that this class is unmeasured, but "
                  f"do not report an AP for it.")

    absent = [n for n in CLASSES if not sum(tally[s][n] for s in tally)]
    if absent:
        print(f"\n  ABSENT from TrafficCAM: {', '.join(absent)}")
        print("  Neither TrafficCAM nor ITD carries these. They can only come")
        print("  from IDD or from our own annotation.")
    if unmapped:
        print(f"\n  UNMAPPED labels, dropped: {dict(unmapped)}")
        print("  Add them to LABEL_MAP or accept the loss deliberately.")
    if dropped:
        print(f"  {dropped} degenerate polygon(s) dropped (zero area)")
    print(f"\n  wrote {yaml}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
